import {presentationTypes,renderFinancialSection} from './financial-presentations.js';
import {bankerValueHTML,readableKey} from './runtime-ui.js';
const num=v=>typeof v==='number'?new Intl.NumberFormat('zh-HK',{maximumFractionDigits:2}).format(v):v??'—';
const labels={open:'待你处理',awaiting_agent:'已回复，待核对',resolved:'已解决',unavailable:'已说明无法提供',archived:'已归档'};
function evidence(rows,esc){return rows?.length?`<details class="business-evidence"><summary>依据</summary>${rows.map(e=>`<blockquote>${esc(e.quote)}<small>${esc(e.locator)}</small></blockquote>`).join('')}</details>`:'';}
function boardHTML(board,esc){return `<section class="supervisor-panel business-board"><h2>${esc(board.title)}</h2><p>${esc(board.summary)}</p>${board.sections.map(s=>presentationTypes.includes(s.type)?renderFinancialSection(s,esc):`<h3>${esc(s.title)}</h3><div class="${s.type==='driver_tree'?'driver-blueprint':'business-rows'}">${s.rows.map(r=>`<article class="business-row"><div><strong>${esc(r.label)}</strong><span class="badge neutral">${{source:'资料数据',proposal:'建议方案',illustration:'示意'}[r.basis]}</span></div>${r.formula?`<div class="business-formula">${esc(r.formula)}</div>`:''}${r.value!=null?bankerValueHTML(r.value,{escape:esc}):''}<p>${esc(r.meaning||'')}</p><small>${esc([r.period,r.unit].filter(Boolean).join(' · '))}</small>${evidence(r.evidence,esc)}</article>`).join('')}</div>`).join('')}</section>`;}
function todoHTML(run,esc){const rows=run.banker?.todos||[],active=rows.filter(t=>['open','awaiting_agent'].includes(t.status)),done=rows.filter(t=>!['open','awaiting_agent'].includes(t.status));const item=t=>`<article class="banker-todo"><div class="supervisor-section-head"><h3>${esc(t.title)}</h3><span class="badge ${t.needs_banker?'warning':'neutral'}">${labels[t.status]}</span></div><p>${esc(t.text)}</p><details><summary>为何需要这项</summary><p>${esc(t.rationale)}</p>${evidence(t.evidence,esc)}</details>${t.last_action?`<p class="todo-outcome"><strong>${t.last_action.actor==='agent'?'华泰建模专家':'你的回复'}：</strong>${esc(t.last_action.text)}</p>`:''}<form data-h-form="todo:${esc(t.id)}" data-h-kind="banker_response" data-todo-id="${esc(t.id)}" data-todo-signature="${esc(t.signature)}"><label>你的答复<textarea name="text" rows="2" required placeholder="直接补充情况；暂时拿不到也可以说明原因。"></textarea></label><div class="button-row"><select name="action" aria-label="如何处理这项待办"><option value="reply">回复，交给华泰建模专家核对</option><option value="resolve">这项已解决</option><option value="unavailable">无法提供，记录原因</option><option value="reopen">重新跟进</option></select><button class="button button-primary">记录并继续</button></div><p data-banker-result role="status"></p></form>${t.history?.length?`<details><summary>处理记录 · ${t.history.length}</summary>${t.history.map(a=>`<p>${esc(a.actor==='agent'?'华泰建模专家':'你')} · ${esc(a.text)}</p>`).join('')}</details>`:''}</article>`;return `<section class="supervisor-panel banker-todos"><h2>Banker 待办 <span class="badge warning">${run.banker?.attention_count||0}</span></h2>${active.length?active.map(item).join(''):'<p>当前没有待你处理的事项。</p>'}${done.length?`<details class="todo-done"><summary>已办记录 · ${done.length}</summary>${done.map(item).join('')}</details>`:''}</section>`;}
function statementsHTML(run,esc){const tables=run.banker?.source_statements||[];return `<section class="supervisor-panel source-statements"><div class="supervisor-section-head"><div><h2>历史报表 · 装配草稿</h2><p>先看已有数字，差异随核对逐项更新。</p></div><span class="badge neutral">来源报表</span></div>${tables.length?tables.map(t=>`<details open><summary>${{pl:'利润表',bs:'资产负债表',cfs:'现金流量表'}[t.kind]} · ${esc(t.sheet)} <small>${esc(t.unit)}</small></summary><div class="table-scroll"><table class="banker-financial-table"><thead><tr><th>项目</th>${t.columns.map(c=>`<th>${esc(c.label)}</th>`).join('')}</tr></thead><tbody>${t.rows.map(r=>`<tr><th>${esc(r.label)}</th>${r.cells.map(c=>`<td class="numeric ${typeof c.value==='string'&&c.value.startsWith('#')?'source-cell-error':''}" title="${esc(c.locator)}">${esc(num(c.value))}</td>`).join('')}</tr>`).join('')}</tbody></table></div><details><summary>查看来源与核对范围</summary><p>${esc(t.source_name)} · ${esc(t.sheet)}</p><p>保留原表的期间、单位和列报数。尚待核对的调整及合并差异可在待办处理。</p><button class="button button-small" data-step="data-room">查看原表</button></details></details>`).join(''):'<div class="chassis-flow"><span>历史利润表</span><i>↔</i><span>资产负债表</span><i>↔</i><span>现金流量表</span></div><p>读到报表后会先列示可用历史，再接变动明细。</p>'}${tables.length&&!tables.some(t=>t.kind==='cfs')?'<p class="field-hint">现金流量表尚未列示；现金余额及非现金变动可先继续核对。</p>':''}</section>`;}
function sketchHTML(run,esc){const seeds=run.banker?.driver_seeds||[];return `<section class="supervisor-panel"><h2>经营驱动 · 讨论草图</h2><p>把已形成的业务判断展开为预测设计；先讨论关系，再补齐数字。</p>${seeds.length?`<div class="driver-blueprint">${seeds.map((i,n)=>`<article class="business-row"><span class="driver-step">${n+1}</span><h3>${esc(i.label)}</h3><div class="business-formula">${typeof i.value==='object'?bankerValueHTML(i.value,{escape:esc}):esc(i.value)}</div><p>${esc(i.rationale)}</p>${evidence(i.evidence,esc)}<button class="button button-small" data-banker-discuss="${esc(i.id)}">讨论这项设计 ↗</button></article>`).join('')}</div>`:'<p>华泰建模专家会根据业务资料提出适用的经营驱动。</p>'}<div class="driver-flow-guide"><span>业务分部 / 客户 / 项目</span><i>→</i><span>经营指标与转化关系</span><i>→</i><span>收入、成本和回款</span></div><p class="field-hint">尚无数据的参数用符号表达，示意数与本版预测分开。</p></section>`;}
export function bankerRoomHTML(run,room,esc){if(!run)return '';const boards=(run.banker?.boards||[]).filter(b=>b.room_id===room);if(room==='todos')return todoHTML(run,esc);if(room==='overview')return `<section class="supervisor-panel room-dispatch"><h2>工作调度</h2><div class="room-headquarters"><strong>华泰建模专家</strong><span>统筹 · 核对 · 融合</span></div><div class="room-dispatch-grid">${(run.workrooms?.rooms||[]).filter(r=>r.activity||r.item_ids?.length||r.board_ids?.length||r.attention_count).map(r=>`<button class="room-dispatch-card ${r.activity?'working':''}" data-step="${esc(r.id)}"><strong>${esc(r.title)}</strong><span>${r.activity?'正在处理':r.attention_count?`${r.attention_count} 项待办`:'已有成果'}</span>${r.activity?`<small>${esc(r.activity.title||'')}</small>`:''}</button>`).join('')}</div>${run.banker?.attention_count?`<button class="button button-primary" data-step="todos">处理 ${run.banker.attention_count} 项待办 →</button>`:''}</section>`;
 let html=specialistHTML(run,room,esc)+boards.map(b=>boardHTML(b,esc)).join('');
 if(room==='drivers'){html+=driverHistoryHTML(run,esc);if(!boards.length)html+=sketchHTML(run,esc);}
 if(room==='chassis')html+=statementsHTML(run,esc);
 if(room==='alchemy'){const items=run.banker?.understanding||[];html+=`<section class="supervisor-panel company-brief"><h2>这家公司的生意</h2>${items.map(i=>`<article><h3>${esc(i.label)}</h3>${bankerValueHTML(i.value,{escape:esc})}<p>${esc(i.rationale)}</p>${evidence(i.evidence,esc)}</article>`).join('')||'<p>资料进入后，先形成业务、市场、经营和现金需求的认识。</p>'}</section>`;}
 if(room==='special'&&!boards.length)html+=`<section class="supervisor-panel"><h2>专项分析</h2><div class="driver-blueprint">${[['盈亏平衡','收入 − 变动成本 − 固定费用 = 0','确定盈亏平衡点及最敏感的经营变量。'],['盈利路径','业务规模 → 毛利贡献 → 费用覆盖 → 盈利','分阶段看何时转盈、依赖哪些经营条件。'],['现金消耗与跑道','可用资金 → 逐月经营、投资及偿债 → 最低现金','区分账面亏损和现金消耗，测试资金可支撑多久。']].map(([title,formula,meaning])=>`<article class="business-row"><h3>${title}</h3><div class="business-formula">${formula}</div><p>${meaning}</p><button class="button" data-banker-special="${title}">请华泰建模专家展开 ↗</button></article>`).join('')}</div></section>`;
 return html;}

function driverHistoryHTML(run,esc){
 const t=run.banker?.source_statements?.find(t=>t.kind==='pl');if(!t)return '';
 const rows=t.rows.filter(r=>/^(revenues?|cost of sales|gross profit|营业收入|营业成本|毛利)$/i.test(r.label.trim()));
 return `<section class="supervisor-panel"><h2>历史经营表现</h2><p>${esc(t.unit)} · ${esc(t.sheet)}</p><div class="table-scroll"><table class="banker-financial-table"><thead><tr><th>项目</th>${t.columns.map(c=>`<th>${esc(c.label)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr><th>${esc(({revenues:'营业收入',revenue:'营业收入','cost of sales':'营业成本','gross profit':'毛利'})[r.label.toLowerCase()]||r.label)}</th>${r.cells.map(c=>`<td class="numeric" title="${esc(c.locator)}">${esc(num(c.value))}</td>`).join('')}</tr>`).join('')}</tbody></table></div><p class="field-hint">历史来源数先行列示；量、价、结构及成本的解释在下方逐项展开。</p></section>`;
}

function specialistHTML(run,room,esc){
 const rows=(run.specialists||[]).filter(s=>s.room_id===room);if(!rows.length)return '';
 const status={running:'正在处理',candidate:'成果待主 agent 核对',failed:'需要重新安排',superseded:'已按新指令调整'};
 return `<section class="supervisor-panel specialist-bench"><h2>本间正在推进</h2>${rows.slice(-5).map(s=>`<article class="business-row"><div><strong>${esc(s.title)}</strong><span class="badge neutral">${esc(status[s.status]||s.status)}</span></div><p>${esc(s.summary||s.packet?.objective||'')}</p>${s.reviews?.length?`<p>${esc(s.reviews.at(-1).rationale||'主 agent 已核对这项候选')}</p>`:''}<details><summary>查看任务与返回成果</summary>${s.result?bankerValueHTML(s.result,{escape:esc}):'<p>专员正在阅读资料与验证。</p>'}</details></article>`).join('')}</section>`;
}
