import {attachmentTargetHTML,createAttachmentController,supportsInlineIntake} from './attachments.js';
import {mountFinancialPresentations,disposeFinancialPresentations} from './financial-presentations.js';
/* Typed business events drive this supervisor workspace. No inferred agent state. */
import {reportingDeskHTML,reportingControlsHTML,reportingTimelineEntries,reportingAttentionHTML,reportingStatus,reportingIsCurrent} from './reporting-desk.js';
import {workerStatusHTML} from './worker-status.js';
import {submissionHTML} from './submission-ui.js';
import {bankerRoomHTML} from './banker-rooms.js';
import {renderFinancialWiring} from './financial-wiring.js';
import {renderBusinessDrivers} from './business-drivers.js';
import {monthlySeries,assumptionChange} from './assumption-edit.js';
import {displayUnit} from './model-units.js';
import {progressLabels,renderInputReceipt} from './input-receipts.js';
import {timeHK,captureScroll,restoreScroll,conversationHTML,toolShelfHTML,bankerValueHTML,valueText,technicalDetailsHTML,syncConversation,workspaceRenderKey,agentTitle} from './runtime-ui.js';
import {ROOMS,roomTitle,roomProjection,visibleItems,roomIntro,financialTables} from './workrooms.js';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const labels={waiting_agent:'准备接续',agent_starting:'连接主 agent',agent_running:'主 agent 正在工作',agent_waiting:'本轮运行已结束',agent_failed:'本轮运行未完成',needs_input:'有事项需要你的判断',input_received:'指令已收到',tool_running:'工具正在计算',paused:'已暂停',cancelled:'已取消',source_changed:'新资料已到，可以建立下一版',succeeded:'已产出结果',failed:'未完成',superseded:'已被新输入替代',running:'计算中',received:'已收到',acknowledged:'已读取',auto_matched:'自动匹配',provisional:'暂定判断',needs_input_item:'请你判断',observation:'来源观察',calibrated:'倒算校准',management_guidance:'管理层指引',agent_assumption:'分析假设',accepted_for_run:'已授权本次采用',rejected:'未采用',proposed:'请你决定',open:'待回复',answered:'回复已收到'};
const sectionLabels={understanding:'公司认识',analysis:'专项分析',scope:'资料与范围',mapping:'科目映射',assumptions:'核心假设',architecture:'建模方式',funding:'融资安排',capability_gap:'需补充的能力'};
const eventLabels={agent_tool_started:'工具开始调用',agent_tool_finished:'工具完成回执',progress_saved:'阶段笔记已保存',source_metadata_saved:'资料用途与日期已记录',runtime_nudge:'运行进展提醒',goal_created:'建立任务',tool_started:'调用工具',tool_finished:'工具返回',context_read:'读取上下文',calculation:'数值测算',workpaper_saved:'更新工作底稿',input_received:'收到你的指令',input_acknowledged:'读取你的指令',input_calculated:'修改已进入试算',completion_proposed:'提出补全方案',request_pack_proposed:'拟好资料清单',request_list_approved:'需求清单已审批',runtime_connected:'主 agent 已连接',agent_consent:'本次资料使用范围已确认',pause:'暂停',resume:'恢复',cancel:'取消'};
const scalar=v=>typeof v==='number'?v:v&&typeof v.source_value==='number'?v.source_value:null;
const numberFormat=new Intl.NumberFormat('zh-CN',{maximumFractionDigits:2});
const fmt=v=>typeof v==='number'?numberFormat.format(v):valueText(v);
const shownValue=i=>{const series=monthlySeries(i.value),format=v=>i.unit==='ratio'?new Intl.NumberFormat('zh-CN',{style:'percent',maximumFractionDigits:2}).format(v):fmt(v);return series.length?series.length===1?`${format(series[0][1])} · ${series[0][0]}`:`${format(series[0][1])} → ${format(series.at(-1)[1])} · ${series.length} 个月`:scalar(i.value)!==null?format(scalar(i.value)):fmt(i.value);};
const roleCopy={memo_librarian:{title:'Memo 知识管理员',rooms:['memo-library'],purpose:'整理已提交的 PFM memo、联席保荐人意见和监管问询回复，保留原文与对应版本关系。',goal:'阅读本次已选择的 PFM memo、联席保荐人意见及监管问询回复，核对每轮文件日期、对应版本、问题和处理结论；整理有出处的候选知识及关联版本说明。保留原文，采用、提交和发布由操作人决定。'},accounting_librarian:{title:'会计知识管理员',rooms:['accounting-library'],purpose:'按具体会计问题检索知识、配平案例和来源，整理可供审阅的处理依据。',goal:'围绕本次会计与配平问题检索已登记知识和案例，核对原始来源、适用条件、会计处理及勾稽关系；整理有出处的候选处理意见和需要补充的证据。知识整理与项目会计结论分别记录，采用和发布由操作人决定。'},audit_reviewer:{title:'项目审阅员',rooms:['audit-lab'],purpose:'审阅本项目的 PFM、memo 与支持资料，核对模型接线、数字假设及披露一致性，记录有出处的问题和复核结果。',goal:'审阅本项目的 PFM、memo、管理层讨论、FDD 和其他已选资料；核对模型接线和勾稽、数字与假设、memo 与模型一致性及相关监管问题。按具体来源、位置、影响和所需修改保存审阅发现，复核修订后更新状态；本任务形成审阅意见，不采用或改写模型。'},source_librarian:{title:'资料管理员',rooms:['intake','data-room'],purpose:'接收资料，识别用途、主体和期间，核对文件之间的关系，整理有出处的标准数据。',goal:'逐份阅读本次收件，核对提取结果并按业务用途分类；从原文识别资料日期、主体和覆盖期间。解释互补、并存、更新或替代关系，保留原文出处及待裁决问题；保存本职责工作间的资料目录、版本关系建议和来源支持的标准数据看板。'},precedent_librarian:{title:'先例图书管理员',rooms:['precedents'],purpose:'按建模需求检索有出处的模板和先例，整理适用条件、差异及审阅建议。',goal:'根据本次需求检索固定版本的模板与先例，核对来源、适用条件、输入输出和与需求的差异；形成有出处的候选目录与审阅建议。采用和发布另经授权，候选记录不自动进入模型或共享库。'}};
roleCopy.intake_librarian={...roleCopy.source_librarian,title:'收件资料管理员',rooms:['intake']};
roleCopy.data_librarian={...roleCopy.source_librarian,title:'标准资料管理员',rooms:['data-room']};
const goalDefault='根据已上传的历史TB和管理层纪要，先理解范围并自动匹配科目与核心假设，选择适合公司的重构和预测方法。先调用工具测算，再解释缺口、业务意义及输出影响；可提出有边界的补全方案与最少Excel资料需求。保存有来源、可修改的工作底稿；模块适用时直接组装三表试算和业务叙事。采用后生成公式Excel与同版中英文memo。';

export function createHarnessController({api,onError,onProject,onSources,onOpenRoom}) {
 let slot=null,project=null,run=null,cap=null,generation=0,timer=null,pending=false,last='',renderKey='',filter='',room='overview',chatOnly=false,reporting=false,roleId='modelling',discussionContext=null;
 const selected=new Map(),drafts=new Map(),inputOrigins=new Map(),openDetails=new Map(),refreshing=new Set();let slotEvents=null;
 const attachments=createAttachmentController({api,onError,getState:()=>({project,run,room,discussionRoom:discussionContext?.room}),onProject:result=>{if(result.project?.id!==project?.id)return;remember();project=result.project;if(onSources)onSources(result);else onProject?.(result);attachments.refresh();clearTimeout(timer);refresh(generation);}});
 const wake=()=>{if(slot){clearTimeout(timer);refresh(generation);}};
 window.addEventListener('focus',wake);
 document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')wake();});
 const sessionKey=()=>`${project.id}:${roleId}`;
 const title=()=>agentTitle(run||{role_id:roleId});
 const roleStatus=()=>roleId==='modelling'?(labels[run?.status]||'查看已有成果'):(labels[run?.status]||'查看已有成果').replace('主 agent',title());
 const steerId=()=>`steer:${roleId==='modelling'?room:roleId}`;
 const consentScope=()=>run&&cap?{route_id:cap.agent.id,source_revision:run.source_revision,source_sha256:run.source_sha256,knowledge_sha256:run.knowledge_sha256}:null;
 const hasPinnedConsent=()=>{const scope=consentScope();return !!scope&&Object.entries(scope).every(([k,v])=>run?.agent_consent?.scope?.[k]===v);};
 function workshopScopeHTML(){
  const library=run?.knowledge_index?.workshop_library;
  const names=[...(library?.sources||[]),...(library?.curations||[])].map(s=>`<li>${esc(s.library)} · ${esc(s.title)}</li>`).join('');
  return names||library?.curation_count?`<details data-h-detail="consent-library"><summary>同时可查的工坊资料</summary><ul>${names}</ul><p>按本次固定版本检索；引用前由主 agent 核对适用性。</p></details>`:'';
 }
 const roleMatches=(value,expected=roleId)=>!!value&&(value.role_id||'modelling')===expected;
 const requireRole=(value,expected=roleId)=>{if(value&&!roleMatches(value,expected))throw new Error('返回的工作职责与当前房间不一致，请重新打开此房间。');return value;};
 const key=(f,n)=>`${sessionKey()}:${run?.id||'new'}:${f}:${n}${f==='start'&&n==='consent'?':'+JSON.stringify(consentScope()):''}`;
 function remember(){slot?.querySelectorAll('[data-h-form]').forEach(f=>f.querySelectorAll('[name]').forEach(e=>{if(e.type!=='file')drafts.set(key(f.dataset.hForm,e.name),e.type==='checkbox'?e.checked:e.value);}));slot?.querySelectorAll('details[data-h-detail]').forEach(d=>openDetails.set(key('detail',d.dataset.hDetail),d.open));}
 function field(label,name,value,type='text',extra=''){return `<label>${esc(label)}<input name="${esc(name)}" type="${type}" value="${esc(value??'')}" ${extra}></label>`;}
 function reply(q,kind='answer') {return `<form data-h-form="${esc(q.id)}" data-h-kind="${kind}">${kind==='answer'&&supportsInlineIntake(roleId)?attachmentTargetHTML({kind:'question',run_id:run.id,target_id:q.id,signature:q.text}):''}<label>${kind==='answer'?'补充资料或给出判断':'你的意见'}<textarea name="text" rows="2" required placeholder="可直接改方向，也可说明已知情况"></textarea></label>${kind!=='answer'?'<label>本次决定<select name="accept" required><option value="">请选择</option><option value="true">同意在上述范围内推进</option><option value="false">调整方案，按我的意见重做</option></select></label>':''}<button class="button button-primary" type="submit">交给 agent 继续</button></form>`;}
 function workpaperHTML(paper){
  if(!paper)return '<div class="supervisor-empty"><span class="supervisor-symbol">↗</span><h2>让 agent 先准备一版</h2><p>读取资料、调用工具、匹配科目与假设；你在这里看成果、提判断、改方向。</p></div>';
  const available=visibleItems(run,room);
  const rows=available.filter(i=>!filter||i.section===filter);
  return `<div class="supervisor-section-head"><div><h2>本间分析与假设</h2></div><span class="badge ${paper.current?'neutral':'warning'}">${paper.current?'当前分析':'前次分析'}</span></div><p>${esc(paper.summary)}</p><div class="supervisor-filters"><button data-h-filter="" class="button button-small ${!filter?'button-primary':''}">全部</button>${Object.entries(sectionLabels).filter(([k])=>available.some(i=>i.section===k)).map(([k,v])=>`<button class="button button-small ${filter===k?'button-primary':''}" data-h-filter="${k}">${v}</button>`).join('')}</div><div class="assumption-cards">${rows.map(i=>{
    const grant=(run.completions||[]).find(c=>c.id===i.completion_id&&c.status==='accepted_for_run');const bound=grant?.targets.find(t=>t.item_id===i.id);
    const series=monthlySeries(i.value);
    const narrative=(run.narratives||[]).slice().reverse().find(n=>n.current&&n.workpaper_id===paper.id)?.items.find(n=>n.item_id===i.id);
    return `<article class="assumption-card"><div class="supervisor-section-head"><strong>${esc(i.label)}</strong><span class="badge ${i.state==='needs_input'?'warning':'neutral'}">${i.state==='needs_input'?'请你判断':bound?'授权范围内补全':esc(labels[i.state])}</span></div><div class="assumption-value ${i.value&&typeof i.value==='object'?'structured-value':''}">${i.value&&typeof i.value==='object'?bankerValueHTML(i.value,{escape:esc,format:v=>i.unit==='ratio'&&typeof v==='number'?new Intl.NumberFormat('zh-CN',{style:'percent',maximumFractionDigits:2}).format(v):valueText(v)}):esc(shownValue(i))}<small>${esc(i.unit==='ratio'?'':displayUnit(i.unit,project))}</small></div><p class="muted">${esc(i.entity||'范围待识别')} · ${esc(i.period||'期间待识别')} · ${esc(labels[i.kind])}</p><p>${esc(narrative?.rendered||i.rationale)}</p>${narrative?'<small class="muted">结合本版完整试算的业务解释</small>':''}${i.question?`<p class="assumption-question">${esc(i.question)}</p>`:''}<details data-h-detail="item-${esc(i.id)}"><summary>查看依据 · 调整这项</summary>${(i.evidence||[]).map(e=>`<blockquote><p>${esc(e.quote)}</p><small>${esc(run.source_index.find(s=>s.id===e.source_id)?.name||e.source_id)} · ${esc(e.locator)}</small></blockquote>`).join('')||'<p class="muted">这是分析判断，来源依据与适用条件需随结果查看。</p>'}<form data-h-form="edit:${esc(i.id)}" data-h-kind="assumption_change" data-item-id="${esc(i.id)}">${technicalDetailsHTML(i.value,{escape:esc,id:`value-${i.id}`})}${series.length?`<label>调整月份<select name="value_month" data-h-month>${series.map(([p])=>`<option value="${esc(p)}">${esc(p)}</option>`).join('')}</select></label>${field(i.unit==='ratio'?'调整比例（0.20 表示 20%）':'调整数值','new_value',series[0][1],'number','step="any"')}`:''}${scalar(i.value)!==null?`${bound?`<input type="range" data-h-slider aria-label="${esc(i.label)} 调整数值" min="${bound.min}" max="${bound.max}" step="any" value="${scalar(i.value)}">`:''}${field(i.unit==='ratio'?'调整比例（0.20 表示 20%）':'调整数值','new_value',scalar(i.value),'number','step="any"')}`:''}<label>你的修改意见<textarea name="text" rows="2" ${scalar(i.value)!==null||series.length?'':'required'} placeholder="直接说明你希望怎么改"></textarea></label><button class="button" type="submit">让 agent 按此重做</button></form></details></article>`;
   }).join('')}</div>`;
 }

 function roleReceipt(input,escape){return renderInputReceipt(input,escape,{showText:false}).replace('主 agent 已读取',`${escape(title())}已读取`);}
 function chatControlsHTML(){
  const copy=roleCopy[roleId],scope=consentScope(),hasConsent=scope&&Object.entries(scope).every(([k,v])=>run?.agent_consent?.scope?.[k]===v),current=run?.source_current&&run?.engine_current!==false&&run?.control!=='cancelled',operating=['starting','running','waiting'].includes(run?.agent_state?.status);
  const picker=`<label class="run-picker">工作记录<select data-h-run><option value="">＋ 新工作目标</option>${(slot._runs||[]).map(r=>`<option value="${esc(r.id)}" ${r.id===run?.id?'selected':''}>${esc(r.goal.slice(0,38))}</option>`).join('')}</select></label>`;
  if(!run)return `<p>${esc(copy?.purpose||'讨论建模目标、资料依据和需要调整的地方。')}</p><p class="field-hint">先建立工作记录，再确认本次资料范围并开始处理。</p>${picker}<form data-h-form="goal" data-h-kind="create"><label>这次需要完成什么<textarea name="goal" rows="5" required maxlength="12000">${esc(copy?.goal||goalDefault)}</textarea></label><button class="button button-primary" type="submit">建立工作任务 →</button><p data-role-result role="status"></p></form>`;
  const sourceNames=(run.source_index||[]).map(s=>`<li>${esc(s.name)}<small> · ${esc(s.sha256?.slice(0,12))}</small></li>`).join('')||'<li>本次来源清单为空。</li>';
  const libraryScope=workshopScopeHTML();
  const permissions=`<details open data-h-detail="consent-sources"><summary>本次资料与服务范围</summary><p>${esc(cap?.agent?.label||'正在读取服务信息')} · 资料版本 ${esc(run.source_revision)}</p><ul>${sourceNames}</ul>${libraryScope}<p>还包括本次目标、你的后续指令及这版固定的工作方法。</p><details data-h-detail="consent-identifiers"><summary>版本校验依据</summary>${bankerValueHTML({scope,sources:run.source_index||[]},{escape:esc})}</details>${run.continued_from?'<p>接续记录来自同一职责的前次工作，采用本次列明的资料范围。</p>':''}</details>`;
  return `<details data-h-detail="role-session"><summary>工作目标与记录</summary><p>${esc(run.goal)}</p>${picker}</details>${run.agent_state?.error?`<p class="notice warning">${esc(run.agent_state.error)}</p>`:''}${!current?`<form data-h-form="continue" data-h-kind="continue"><p>资料或工作状态已变化，请按当前资料建立接续记录。</p><label>接续目标<textarea name="text" required rows="3">${esc(run.goal)}</textarea></label><button class="button button-primary" type="submit">建立接续记录</button></form>`:(!operating||!hasConsent)?`<form data-h-form="start" data-h-kind="start">${!hasConsent?`${permissions}<label class="check-label"><input name="consent" type="checkbox" required>同意${esc(title())}按上述范围处理本次任务</label>`:''}<button class="button button-primary" type="submit" ${!cap?.agent?.available?'disabled':''}>${hasConsent?'接续工作':'确认范围并开始'}</button><p data-role-result role="status"></p></form>`:`<p class="supervisor-status"><span data-run-summary>${esc(roleStatus())}</span><button class="button button-small" data-h-control="${run.control==='paused'?'resume':'pause'}">${run.control==='paused'?'继续':'暂停'}</button></p>`}`;
 }
 function roleProgressHTML(){
  if(!run||roleId==='modelling')return '';
  const rooms=roleCopy[roleId]?.rooms||[],latest=new Map();for(const board of run.business_boards||run.banker?.boards||[])if(rooms.includes(board.room_id))latest.set(board.id,board);
  const boards=[...latest.values()];if(!boards.length)return '';
  return `<details data-h-detail="role-progress"><summary>已整理 ${boards.length} 项 · ${esc(boards.at(-1).title)}</summary>${boards.map(b=>`<article><strong>${esc(b.title)}</strong><p>${esc(b.summary)}</p>${(b.sections||[]).map(s=>`<details><summary>${esc(s.title)}</summary>${(s.rows||[]).map(r=>`<p><strong>${esc(r.label)}</strong></p>${r.value==null?'':bankerValueHTML(r.value,{escape:esc})}<p>${esc(r.meaning||'')}</p>`).join('')}</details>`).join('')}</article>`).join('')}</details>`;
 }
 function standaloneHTML(){
  const current=run?.source_current&&run?.engine_current!==false&&run?.control!=='cancelled',canSend=current&&(roleId==='modelling'||hasPinnedConsent());
  const conversation=run?conversationHTML(run,esc,roleReceipt).replace('<div data-conversation-messages>',`<div data-librarian-controls>${chatControlsHTML()}</div><div data-role-progress>${roleProgressHTML()}</div><div data-conversation-messages>`):`<div class="agent-conversation" data-role-startup><div data-librarian-controls>${chatControlsHTML()}</div></div>`;
  return `<aside class="supervisor-live-chat" data-live-chat data-run-id="${esc(run?.id||'')}" data-role-id="${esc(roleId)}"><div class="live-chat-head"><strong>${esc(title())}</strong><span>${esc({'intake':'收件室','data-room':'标准件房','precedents':'先例工坊','accounting-library':'会计与配平工坊','memo-library':'PFM Memo 工坊','audit-lab':'审核工坊'}[room]||roomTitle(room))}</span></div>${conversation}${run?`<button class="button button-small chat-latest" data-chat-latest>查看最新进展 ↓</button><form class="live-chat-composer" data-h-form="${esc(steerId())}" data-h-kind="steer"><label><span class="sr-only">给${esc(title())}发消息</span><textarea name="text" rows="3" required placeholder="讨论资料、说明已知情况或提出调整…"></textarea></label>${supportsInlineIntake(roleId)?attachmentTargetHTML({kind:'chat'}):''}<label>处理方式<select name="intent"><option value="revision">按此继续工作</option><option value="discussion">先讨论、解释</option></select></label><button class="button button-primary" type="submit" ${!canSend?'disabled':''}>发送 ↗</button>${!current?'<small>请先建立接续记录。</small>':!canSend?'<small>请先确认上方资料与服务范围。</small>':''}</form>`:''}</aside>`;
 }
 function restoreChatFields(focus){
  slot.querySelectorAll('[data-h-form]').forEach(f=>f.querySelectorAll('[name]').forEach(e=>{const value=drafts.get(key(f.dataset.hForm,e.name));if(value!==undefined&&e.type!=='file'){if(e.type==='checkbox')e.checked=value;else e.value=value;}}));
  slot.querySelectorAll('details[data-h-detail]').forEach(d=>{d.open=openDetails.get(key('detail',d.dataset.hDetail))??d.open;});
  if(focus){const form=[...slot.querySelectorAll('[data-h-form]')].find(f=>f.dataset.hForm===focus.form),element=form?.elements.namedItem(focus.name);element?.focus({preventScroll:true});if(element?.setSelectionRange&&focus.start!==null&&['textarea','text'].includes(element.type))element.setSelectionRange(focus.start,focus.end);}
 }
 function chatFocus(){const active=slot?.contains(document.activeElement)?document.activeElement:null;return active?.name?{form:active.closest('[data-h-form]')?.dataset.hForm,name:active.name,start:active.selectionStart,end:active.selectionEnd}:null;}
 function renderStandalone(){
  if(run&&slot.querySelector('[data-live-chat]')?.dataset.runId===run.id){patchRuntime();renderKey=workspaceRenderKey(run);announceRun();return;}
  const focus=chatFocus(),scrolls=captureScroll(slot);slot.innerHTML=standaloneHTML();slot._controlHTML=chatControlsHTML();slot._progressHTML=roleProgressHTML();restoreChatFields(focus);restoreScroll(slot,scrolls);if(run&&roleId!=='modelling'&&!hasPinnedConsent())slot.querySelector('.agent-conversation').scrollTop=0;slot._consentScope=consentScope();renderKey=workspaceRenderKey(run);announceRun();
 }
 function syncStandalone(){
  const focus=chatFocus(),scrolls=captureScroll(slot),controls=chatControlsHTML(),progress=roleProgressHTML(),controlsChanged=controls!==slot._controlHTML;
  if(controls!==slot._controlHTML){const container=[...slot.querySelectorAll('[data-librarian-controls]')].find(n=>!n.closest('[data-role-startup]'));if(container){container.innerHTML=controls;slot._controlHTML=controls;restoreChatFields(focus);}}
  if(progress!==slot._progressHTML){const container=slot.querySelector('[data-role-progress]');if(container){container.innerHTML=progress;slot._progressHTML=progress;restoreChatFields(focus);}}
  slot._consentScope=consentScope();restoreScroll(slot,scrolls);if(controlsChanged&&roleId!=='modelling'&&!hasPinnedConsent())slot.querySelector('.agent-conversation').scrollTop=0;
 }

 function currentDiscussionContext(){
  if(discussionContext&&(discussionContext.projectId!==project?.id||discussionContext.runId!==(run?.id||null)||discussionContext.roleId!==roleId))discussionContext=null;
  return discussionContext;
 }
 function syncDiscussionContext(){
  const context=currentDiscussionContext(),chip=slot?.querySelector('[data-reporting-context]');
  if(!chip)return;chip.hidden=!context;const label=chip.querySelector('[data-reporting-context-label]');if(label)label.textContent=context?'讨论：'+context.label:'';
  attachments.refresh();
 }
 function setDiscussionContext(roomId,label=''){
  if(!slot||!reporting)return false;
  if(roomId==null||roomId===''){discussionContext=null;syncDiscussionContext();return true;}
  const allowed=roleId==='modelling'?['overview',...ROOMS.map(([id])=>id)]:roleCopy[roleId]?.rooms||[];
  if(typeof roomId!=='string'||!allowed.includes(roomId))return false;
  discussionContext={room:roomId,label:typeof label==='string'&&label.trim()?label.trim():ROOMS.find(([id])=>id===roomId)?.[1]||({overview:'项目汇报桌',intake:'收件室','data-room':'标准件房',precedents:'先例工坊','accounting-library':'会计与配平工坊','memo-library':'PFM Memo 工坊','audit-lab':'审核工坊'}[roomId]||roomId),projectId:project.id,runId:run?.id||null,roleId};
  syncDiscussionContext();return true;
 }
 function reportingOptions(){return {run,roleId,room,discussionContext:currentDiscussionContext(),steerId:steerId(),runs:slot?._runs||[],cap,scope:consentScope(),hasConsent:hasPinnedConsent(),scopeHTML:workshopScopeHTML(),pending,receipt:roleReceipt};}
 function syncReporting(){
  if(!slot)return;
  const focus=chatFocus(),scrolls=captureScroll(slot),options=reportingOptions();syncDiscussionContext();
  if(run)syncConversation(slot,run,esc,roleReceipt,{attachments:reportingTimelineEntries(run,roleId),beforeRemove:disposeFinancialPresentations});
  const fragments=[['controls',reportingControlsHTML(options)],['worker',workerStatusHTML(run)],['attention',reportingAttentionHTML(run)]];
  for(const [name,html]of fragments){const node=slot.querySelector(`[data-reporting-${name}]`);if(node&&node._reportingHTML!==html){disposeFinancialPresentations(node);node.innerHTML=html;node._reportingHTML=html;}}
  const latest=slot.querySelector('[data-chat-latest]');if(latest)latest.hidden=!run?.live_message?.text&&!(run?.events||[]).some(e=>['agent_message','input_received'].includes(e.kind));
  const empty=slot.querySelector('[data-conversation-empty]');if(empty)empty.textContent='讨论和处理进展会保存在这里。';
  const status=slot.querySelector('[data-reporting-status]');if(status)status.textContent=reportingStatus(run);
  slot.querySelector('[data-reporting-dot]')?.classList.toggle('active',reportingIsCurrent(run)&&run.control!=='paused'&&(['starting','running'].includes(run.agent_state?.status)||(run.worker_state?.current&&['starting','running'].includes(run.worker_state.status))));
  const composer=slot.querySelector('.reporting-composer'),current=reportingIsCurrent(run),canSend=!run||current&&hasPinnedConsent()&&run.control!=='paused';
  if(composer){const button=composer.querySelector('button[type=submit]');if(button)button.disabled=!canSend||pending;const hint=composer.querySelector('[data-reporting-composer-hint]');if(hint){hint.hidden=canSend;hint.textContent=run?.control==='paused'?'工作已暂停，点击上方继续工作。':current?'请先确认上方资料与服务范围。':'请先按当前资料建立接续记录。';}}
  slot.querySelectorAll('[data-reporting-attention] button[type=submit]').forEach(button=>{button.disabled=!current||!hasPinnedConsent()||pending||run?.control==='paused';});
  restoreChatFields(focus);
  const paperId=run?.workpapers?.at(-1)?.id||null;
  for(const form of slot.querySelectorAll('[data-h-form]')){const origin=key(form.dataset.hForm,'origin'),prior=form.querySelector('[data-reporting-stale]');if(inputOrigins.has(origin)&&inputOrigins.get(origin)!==paperId){if(!prior)form.insertAdjacentHTML('afterbegin','<p class="notice warning" data-reporting-stale>这段回复开始于前版底稿，请核对后继续。 <button type="button" class="button button-small" data-h-rebase>已核对</button></p>');}else prior?.remove();}
  slot._consentScope=consentScope();restoreScroll(slot,scrolls);mountFinancialPresentations(slot);attachments.refresh();
 }
 function renderReporting(){
  if(slot.querySelector('.reporting-desk')?.dataset.runId===(run?.id||'')){syncReporting();renderKey=workspaceRenderKey(run);announceRun();return;}
  const focus=chatFocus(),scrolls=captureScroll(slot);slot.innerHTML=reportingDeskHTML(reportingOptions());syncReporting();restoreChatFields(focus);restoreScroll(slot,scrolls);renderKey=workspaceRenderKey(run);announceRun();
 }
 function render(){
  if(!slot)return;
  if(reporting){renderReporting();return;}
  if(chatOnly){renderStandalone();return;}
  const scrolls=captureScroll(slot);const pageY=window.scrollY;const keptChat=slot.querySelector('[data-live-chat]');
  const active=slot.contains(document.activeElement)?document.activeElement:null;
  const focus=active?.name?{f:active.closest('[data-h-form]')?.dataset.hForm,n:active.name,start:active.selectionStart,end:active.selectionEnd}:null;
  const paper=run?.workpapers?.at(-1), questions=run?.questions?.filter(q=>q.status==='open')||[];
  const current=run?.source_current&&run?.engine_current!==false&&run.control!=='cancelled';const operating=['starting','running','waiting'].includes(run?.agent_state?.status);
  const calculated=(run?.calls||[]).filter(c=>c.tool==='model_definition'&&c.status==='succeeded');
  const models=run?.models||[];const showLegacyQuestions=['overview','todos'].includes(room);
  const messages=run?.events?.filter(e=>e.kind==='agent_message')||[];
  const scope=consentScope();
  const hasConsent=scope&&Object.entries(scope).every(([k,v])=>run?.agent_consent?.scope?.[k]===v);
  const projection=roomProjection(run,room);
  const calls=room==='overview'?(run?.calls||[]):(run?.calls||[]).filter(c=>projection?.call_ids?.includes(c.id));
  const documents=room==='overview'?(run?.documents||[]):(run?.documents||[]).filter(d=>projection?.document_ids?.includes(d.id));
  const showModel=['overview','drivers','chassis','assembly','treasury','quality','dispatch'].includes(room);
  slot.classList.toggle('harness-with-chat',!!run&&!chatOnly);
  disposeFinancialPresentations(slot);
  slot.innerHTML=`<div class="supervisor-heading"><div><h1>${esc(roomTitle(room))}</h1></div><button class="button" data-step="intake">收件室 ↗</button></div>
   ${run?`<div class="banker-run-bar"><span data-run-summary>${esc(labels[run.status]||'查看已有成果')}</span>${run.banker?.attention_count?`<button class="button button-small" data-step="todos">${run.banker.attention_count} 项待办 →</button>`:''}${!current||!operating||run.control==='paused'?'<button class="button button-small" data-open-mission>继续工作 →</button>':'<button class="button button-small" data-h-control="pause">暂停</button>'}</div>`:''}
   ${roomIntro(run,project,room,esc)}
   <details class="supervisor-mission" data-h-detail="mission" ${!run?'open':''}><summary>工作目标与设置</summary><div class="supervisor-section-head"><span class="eyebrow">本次工作</span><label class="run-picker">工作版本<select data-h-run><option value="">＋ 新工作目标</option>${(slot._runs||[]).map(r=>`<option value="${esc(r.id)}" ${r.id===run?.id?'selected':''}>${esc(r.goal.slice(0,38))} · r${r.source_revision}</option>`).join('')}</select></label></div><details data-h-detail="versions-help"><summary>工作版本与接续如何保存</summary><p>项目保存资料、版本关系和全部工作记录。同一工作版本内，接续恢复同一个 agent 会话；用户新指令另记一轮。资料、工具包或目标改变时，可带着原有记录建立新的工作版本。旧版留存可查。</p><p>阶段笔记和底稿由 Model Studio 保存；原生对话由本机 Codex 会话保存。工作版本之间通过明确的接续关系交接。</p></details>
   ${run?`<p class="harness-goal">${esc(run.goal)}</p><div class="supervisor-status" role="status" data-h-status><span class="activity-dot ${['agent_running','tool_running','agent_starting'].includes(run.status)?'active':''}"></span><strong>${esc(labels[run.status]||run.status)}</strong><span>资料版本 ${run.source_revision}</span>${run.control!=='cancelled'?`<button class="button button-small" data-h-control="${run.control==='paused'?'resume':'pause'}">${run.control==='paused'?'继续':'暂停'}</button>`:''}</div><details data-h-detail="connection"><summary>运行详情</summary><p class="muted" data-h-agent-detail>${esc(run.agent_state?.detail||'目标已保存，接通主 agent 后开始读取资料。')}</p>${run.runtime_activity?`<p class="runtime-health"><span class="activity-dot ${['running','starting'].includes(run.agent_state?.status)&&run.runtime_activity.process_alive?'active':''}"></span>${esc(timeHK(run.runtime_activity.checked_at))} · ${['running','starting'].includes(run.agent_state?.status)?(run.runtime_activity.process_alive?'运行器在线':'连接待恢复'):'最近一次连接检查'} · 香港时间<br><small>${run.runtime_activity.running_tools?`有 ${run.runtime_activity.running_tools} 项工具调用正在处理`:`距上次公开进展 ${run.runtime_activity.public_silence_seconds} 秒`}；连接检查不等于新结论。</small></p>`:''}</details>${run.agent_state?.error?`<p class="notice warning">${esc(run.agent_state.error)}</p>`:''}
    ${!current?`<form data-h-form="continue" data-h-kind="continue"><p>${run.control==='cancelled'?'本次工作已由你结束。':run.engine_current===false?'工作包已更新。':'项目资料已有更新。'}可以保留并接回已读记录、公开说明、阶段笔记与底稿；不继承旧版采用或授权。</p><label>本次目标<textarea name="text" rows="2" required>${esc(run.goal)}</textarea></label><button class="button button-primary" type="submit">带着已有工作建立接续版</button></form>`:''}
    ${!operating&&current?`<form data-h-form="start" data-h-kind="start">${!hasConsent?`<details data-h-detail="consent-sources"><summary>本次交给 agent 的资料范围</summary><p>${esc(cap?.agent?.label||'正在读取服务信息')} · 固定版本 ${run.source_revision}。包括本任务目标、项目资料、后续指令和版本化SOP/工具包。</p><ul>${run.source_index.map(s=>`<li>${esc(s.name)} <small>${esc(s.sha256?.slice(0,12))}</small></li>`).join('')}</ul>${workshopScopeHTML()}<p>本版可按需读取的项目方法：${(run.knowledge_index.project_methods?.resources||[]).map(m=>esc(m.title)).join('；')||'沿用本版已列明的通用 SOP'}。项目 skill 可能包含历史项目案例和操作路径；不会自动读取所指原始文件。</p>${run.continued_from?'<p>同时包含明确接续的前版工作记录；前版授权不转为本版采用。</p>':''}</details><label class="check-label"><input name="consent" type="checkbox" required>同意主 agent 使用上述资料与服务完成本次任务</label>`:''}<button class="button button-primary" type="submit" ${!cap?.agent?.available?'disabled':''}>${hasConsent?'接续工作':'启动主 agent'}</button></form>`:''}`:
    `<form data-h-form="goal" data-h-kind="create"><label>告诉 agent 这次要完成什么<textarea name="goal" rows="4" required maxlength="12000">${esc(goalDefault)}</textarea></label><button class="button button-primary" type="submit">建立工作任务 →</button></form>`}</details>
   ${showModel&&(calculated.length||models.length)?`<section class="supervisor-panel"><h2>模型与本版采用</h2>${calculated.slice(-1).map(c=>{const r=c.result.report,m=r.model,failed=m.checks.filter(x=>!x.passed);return `<article class="model-version-card"><p><strong>底稿已进入公式三表试算</strong> · ${c.current?'当前试算':'前版试算'}</p><dl class="harness-metrics">${[['预测收入',m.summary.revenue],['预测净利润',m.summary.net_income],['最低现金',m.summary.min_cash],['期末借款',m.summary.closing_debt]].map(([label,value])=>`<div><dt>${label}</dt><dd>${esc(fmt(value))}</dd></div>`).join('')}</dl><p class="muted">${esc(m.currency)} · ${esc(m.unit)} · ${esc(m.periods[0])} 至 ${esc(m.periods.at(-1))}</p>${['assembly','treasury'].includes(room)?financialTables(m,esc,fmt,room):''}${['overview','drivers','assembly','special'].includes(room)?renderBusinessDrivers(m.driver_composition,{escape:esc,format:fmt,id:c.id,context:m}):''}${['overview','chassis','quality'].includes(room)?renderFinancialWiring(m.financial_wiring,{escape:esc,format:fmt,id:c.id}):''}${failed.map(f=>`<p class="notice warning"><strong>${esc(f.label||f.id)}</strong> · ${esc(f.period)} · ${esc(f.value)}</p>`).join('')}<details data-h-detail="policies-${c.id}"><summary>所选模块、政策和仍需复核的范围</summary><p>${esc(r.definition.module_id)}</p>${bankerValueHTML(m.coverage.policies,{escape:esc})}${technicalDetailsHTML(m.coverage.policies,{escape:esc,id:`policy-source-${c.id}`})}${m.gaps.map(g=>`<p>${esc(g.message)}</p>`).join('')}</details>${c.current?`<form data-h-form="adopt:${c.id}" data-h-kind="adopt_model" data-target-id="${c.id}">${field('本版建模责任人','responsible_person','', 'text','required')}<label>采用说明<textarea name="text" required rows="2" placeholder="采用这版作为工作情景；需调整时可直接在下方告诉 agent"></textarea></label><p class="field-hint">一次采用本版列明的科目、假设和政策；原始指引、暂定假设与公司确认仍分别保留。</p><button class="button button-primary" type="submit" ${failed.length?'disabled':''}>采用本版输入，交给 agent 生成工作簿</button></form>`:''}</article>`;}).join('')}${models.map(m=>`<p><strong>${m.current?'本版已采用并计算':'保留的前版模型'}</strong> · ${esc(m.id.slice(0,8))} · ${esc(m.adoption.responsible_person)}</p>`).join('')}${(run?.calls||[]).filter(c=>c.tool==='model_export'&&c.status==='succeeded').map(c=>`<a class="button" href="/api/harness/${run.id}/artifacts/${c.id}">下载公式 Excel · ${esc(c.id.slice(0,8))}${c.current?'':'（前版）'}</a>`).join('')}</section>`:''}
   <div class="supervisor-grid"><div class="supervisor-main">${bankerRoomHTML(run,room,esc)}${['alchemy','drivers','chassis','special','todos'].includes(room)?`<details class="supervisor-panel" data-h-detail="supporting-workpaper"><summary>分析底稿与来源依据</summary>${workpaperHTML(paper)}</details>`:`<section class="supervisor-panel">${workpaperHTML(paper)}</section>`}
    ${run?.progress_notes?.length?`<details class="supervisor-panel" data-h-detail="saved-notes"><summary>工作笔记</summary><p>${esc(run.progress_notes.at(-1).summary)}</p><p class="muted">下一步：${esc(run.progress_notes.at(-1).next_steps)}</p><details data-h-detail="progress-notes"><summary>查看全部 ${run.progress_notes.length} 次保存</summary>${run.progress_notes.map(n=>`<article><time>${esc(timeHK(n.at))}</time><p>${esc(n.summary)}</p><p>${esc(n.next_steps)}</p></article>`).join('')}</details></details>`:''}${run?.carryover?`<details class="supervisor-panel" data-h-detail="previous-work"><summary>前次工作记录</summary><p>保留了前版的输入、问题、阶段记录和底稿引用。主 agent 需结合当前资料核对适用性。</p><p>${esc(run.carryover.workpaper?.summary||'前版尚未成功保存工作底稿；已接回公开说明与调用记录。')}</p><details data-h-detail="carryover"><summary>前版公开说明</summary>${(run.carryover.messages||[]).map(e=>`<p class="harness-verbatim">${esc(e.payload.text)}</p>`).join('')}</details></details>`:''}
    ${calls.length?`<details class="supervisor-panel" data-h-detail="room-calculations"><summary>查看计算过程与结果</summary>${calls.map(c=>`<details class="tool-card" data-h-detail="call-${c.id}"><summary><span>${esc(c.label)}</span><span class="badge neutral">${esc(labels[c.status]||c.status)}${c.status==='succeeded'&&!c.current?' · 前版':''}</span></summary>${c.result?.view?`<p>${esc(c.result.view.summary)}</p><dl class="harness-metrics">${c.result.view.metrics.map(m=>`<div><dt>${esc(m.label)}</dt><dd>${esc(fmt(m.value))}</dd></div>`).join('')}</dl><p class="muted">${esc(c.result.view.note)}</p>`:''}${c.error?`<p>${esc(c.error)}</p>`:''}${(c.result?.view?.issues||[]).map(i=>`<p class="notice warning">${esc(i.label)} · ${esc(i.detail)}</p>`).join('')}<details><summary>技术明细与完整计算记录</summary><pre>${esc(JSON.stringify(c.result?.report||{},null,2))}</pre></details></details>`).join('')}</details>`:''}
   </div><aside class="supervisor-side">${showLegacyQuestions?`<section class="supervisor-panel"><span class="eyebrow">需要你介入</span><h2>关键判断与资料</h2>${!questions.length&&!run?.banker?.todos?.some(t=>['open','awaiting_agent'].includes(t.status))&&!run?.decisions.some(d=>d.status==='proposed')&&!run?.completions?.some(c=>c.status==='proposed')?'<p class="muted">目前没有需要你处理的事项。Agent 会先完成可独立推进的工作。</p>':''}
    ${(run?.completions||[]).filter(c=>c.status==='proposed'&&c.epoch===run.epoch).map(c=>`<article class="harness-item"><h3>${esc(c.title)}</h3><p>${esc(c.rationale)}</p><ul>${c.targets.map(t=>`<li><strong>${esc(t.label)}：${t.min}–${t.max} ${esc(t.unit)}</strong><br>${esc(t.entity)} · ${esc(t.period)}<br>${esc(t.method)}<br><small>替换条件：${esc(t.replacement_trigger)}</small></li>`).join('')}</ul>${reply(c,'completion_response')}</article>`).join('')}
    ${questions.map(q=>`<article class="harness-item"><h3>${esc(q.text)}</h3><p>${esc(q.rationale)}</p>${reply(q)}</article>`).join('')}
    ${(run?.decisions||[]).filter(d=>d.status==='proposed'&&d.epoch===run.epoch).map(d=>`<article class="harness-item"><h3>${esc(d.text)}</h3><p>${esc(d.rationale)}</p>${reply(d,'decision_response')}</article>`).join('')}
   </section>`:''}<section class="supervisor-panel">${toolShelfHTML(cap,run,room,projection,esc)}</section></aside></div>
   ${room==='dispatch'?submissionHTML(run,esc):''}${documents.length?`<section class="supervisor-panel"><h2>会议准备与交付文稿</h2>${documents.map(d=>`<article class="harness-item"><h3>${esc(d.title_zh)}</h3><p class="muted">${d.current?'本版文稿':'保留的前版文稿'} · ${d.kind==='profit_forecast_memo'?'同一模型版本的中英文复核稿':'针对本项目资料的讨论与跟进稿'}</p><a class="button" target="_blank" rel="noopener" href="/api/harness/${run.id}/documents/${d.id}?language=en">English</a> <a class="button" target="_blank" rel="noopener" href="/api/harness/${run.id}/documents/${d.id}?language=zh">中文</a> <a class="button" target="_blank" rel="noopener" href="/api/harness/${run.id}/documents/${d.id}">中英对照</a><details data-h-detail="doc-${d.id}"><summary>预览内容</summary>${d.sections.map(s=>`<h4>${esc(s.title_zh)}</h4><p class="harness-verbatim">${esc(s.zh_rendered)}</p>`).join('')}</details></article>`).join('')}</section>`:''}
   ${run?`<section class="supervisor-panel"><h2>资料需求 · 审阅后交给客户填写</h2>${(run.request_drafts||[]).filter(d=>d.epoch===run.epoch).map(d=>`<details data-h-detail="request-${d.id}"><summary>${esc(d.purpose)} · 审阅与编辑</summary><p>${esc(d.explanation)}</p><form data-h-form="request:${d.id}" data-h-kind="approve_request_pack" data-target-id="${d.id}">${field('用途','purpose',d.purpose)}<div class="request-edit-grid">${d.fields.map((f,i)=>`<div><strong>${esc(f.id)}</strong>${field('请客户填写的内容','label_'+i,f.label)}${field('主体 / 范围','entity_'+i,f.entity)}${field('期间','period_'+i,f.period)}${field('单位','unit_'+i,f.unit)}<label>需求优先级<select name="priority_${i}"><option value="core" ${f.priority==='core'?'selected':''}>核心</option><option value="ancillary" ${f.priority==='ancillary'?'selected':''}>辅助</option></select></label>${field('建模用途','model_use_'+i,f.model_use)}</div>`).join('')}</div><button class="button button-primary" type="submit">批准并生成可填写 Excel</button></form></details>`).join('')||'<p class="muted">需要额外资料时，agent 会先拟好最少填写项，供你审阅。</p>'}
    ${(run.request_lists||[]).map(p=>`<article class="harness-item"><a class="button" href="/api/harness/${run.id}/request-lists/${p.id}">下载已审批${p.format==='xlsx'?' Excel':'需求清单'}</a><span class="muted">已生成审批记录 · 尚未发送</span>${p.format==='xlsx'?`${attachmentTargetHTML({kind:'request_return',run_id:run.id,target_id:p.id},{returnFile:true})}`:''}</article>`).join('')}
   </section><details class="supervisor-panel" data-h-detail="process-record"><summary>过程记录与版本依据</summary><div class="supervisor-section-head"><button class="button button-small" data-h-control="cancel" ${run.control==='cancelled'?'disabled':''}>结束本次运行</button></div><details data-h-detail="events"><summary>查看真实调用、输入及版本记录</summary><ol class="harness-events" data-live-scroll="events:${run.id}">${run.events.filter(e=>e.kind!=='agent_message').map(e=>`<li value="${e.seq}" data-event-id="${esc(e.id)}"><strong>${esc(eventLabels[e.kind]||e.kind==='agent_state'&&e.payload.detail||e.kind)}</strong> <span>${esc(e.payload.title||e.payload.label||e.payload.summary||'')}</span><small>${esc(timeHK(e.at))} 香港</small></li>`).join('')}</ol></details>
    ${paper?`<details data-h-detail="rework"><summary>交付后返工 · 从这版另建修改任务</summary><form data-h-form="rework" data-h-kind="rework"><label>基于底稿 V${paper.version} 的修改要求<textarea name="text" required rows="2"></textarea></label><button class="button" type="submit">保留本版，建立返工任务</button></form></details>`:''}</details>
   <aside class="supervisor-live-chat" data-live-chat data-run-id="${esc(run.id)}"><div class="live-chat-head"><strong>${esc(title())}</strong><span>${esc(roomTitle(room))}</span></div>${conversationHTML(run,esc,roleReceipt)}<button class="button button-small chat-latest" data-chat-latest>查看最新进展 ↓</button><form class="live-chat-composer" data-h-form="${esc(steerId())}" data-h-kind="steer"><label><span class="sr-only">给${esc(title())}发消息</span><textarea name="text" rows="3" required placeholder="直接讨论，或随时告诉我怎么调整…"></textarea></label>${supportsInlineIntake(roleId)?attachmentTargetHTML({kind:'chat'}):''}<label>处理方式<select name="intent"><option value="revision">修改工作版</option><option value="trial">先试算方案</option><option value="discussion">先讨论、解释</option></select></label><button class="button button-primary" type="submit" ${!current?'disabled':''}>发送 ↗</button>${!current?'<small>本工作版本已停止或已有新版；先建立接续版。</small>':''}</form></aside>`:''}`;
  const newChat=slot.querySelector('[data-live-chat]');if(keptChat&&newChat&&keptChat.dataset.runId===run?.id){newChat.replaceWith(keptChat);syncConversation(keptChat,run,esc,roleReceipt);const send=keptChat.querySelector('button[type=submit]');if(send)send.disabled=!current;const oldHint=keptChat.querySelector('.live-chat-composer>small');if(current)oldHint?.remove();else if(!oldHint)keptChat.querySelector('.live-chat-composer').insertAdjacentHTML('beforeend','<small>本工作版本已停止或已有新版；先建立接续版。</small>');}
  if(chatOnly){const chat=slot.querySelector('[data-live-chat]');slot.replaceChildren(...(chat?[chat]:[]));}
  restoreScroll(slot,scrolls);window.scrollTo({top:pageY,behavior:'instant'});
  slot.querySelectorAll('[data-h-form]').forEach(f=>f.querySelectorAll('[name]').forEach(e=>{const v=drafts.get(key(f.dataset.hForm,e.name));if(v!==undefined&&e.type!=='file'){if(e.type==='checkbox')e.checked=v;else e.value=v;}}));
  slot.querySelectorAll('details[data-h-detail]').forEach(d=>{d.open=openDetails.get(key('detail',d.dataset.hDetail))??d.open;});
  if(focus){const f=[...slot.querySelectorAll('[data-h-form]')].find(f=>f.dataset.hForm===focus.f);const e=f?.elements.namedItem(focus.n);e?.focus({preventScroll:true});if(e?.setSelectionRange&&focus.start!==null&&['textarea','text'].includes(e.type))e.setSelectionRange(focus.start,focus.end);}
  slot.querySelectorAll('[data-h-form]').forEach(f=>{const k=key(f.dataset.hForm,'origin');if(inputOrigins.has(k)&&inputOrigins.get(k)!==(paper?.id||null)){f.insertAdjacentHTML('afterbegin','<p class="notice warning">这段输入开始于较早底稿。原话已保留；请先核对本版内容。<button type="button" class="button button-small" data-h-rebase>我已核对，按当前版提出</button></p>');}});
  slot._consentScope=scope;renderKey=workspaceRenderKey(run);announceRun();
 }
 function announceRun(){attachments.refresh();if(slot)mountFinancialPresentations(slot);slot?.dispatchEvent(new CustomEvent('model-studio-room-update',{bubbles:true,detail:{run,room,roleId,projectId:project.id}}));}
 function patchRuntime(){
  if(!slot||!run)return;
  if(reporting){syncReporting();return;}
  syncConversation(slot,run,esc,roleReceipt);if(chatOnly)syncStandalone();
  const composer=slot.querySelector('form.live-chat-composer'),current=run.source_current&&run.engine_current!==false&&run.control!=='cancelled';if(composer){const send=composer.querySelector('button[type=submit]');const canSend=current&&(roleId==='modelling'||hasPinnedConsent());if(send)send.disabled=!canSend||pending;const hint=composer.querySelector(':scope>small');if(canSend)hint?.remove();else {const text=current?'请先确认上方资料与服务范围。':'本工作版本已停止或已有新版；先建立接续版。';if(hint)hint.textContent=text;else composer.insertAdjacentHTML('beforeend',`<small>${text}</small>`);}}
  const status=slot.querySelector('[data-h-status]');if(status){const label=status.querySelector('strong');const text=labels[run.status]||run.status;if(label.textContent!==text)label.textContent=text;status.querySelector('.activity-dot')?.classList.toggle('active',['agent_running','tool_running','agent_starting'].includes(run.status));}
  const detail=slot.querySelector('[data-h-agent-detail]');if(detail&&detail.textContent!==run.agent_state?.detail)detail.textContent=run.agent_state?.detail||'目标已保存';
  const summary=slot.querySelector('[data-run-summary]');if(summary)summary.textContent=roleStatus();
 }
 async function refresh(g=generation){if(!slot||refreshing.has(g))return;refreshing.add(g);try{const id=selected.get(sessionKey());const data=id?await api(`/api/harness/${id}`):null;if(g!==generation)return;const value=requireRole(data?.run||null);const next=workspaceRenderKey(value);if(next!==renderKey){remember();run=value;last=next;if(run&&(chatOnly||reporting)&&slot.querySelector('[data-live-chat]')?.dataset.runId===run.id){patchRuntime();renderKey=next;announceRun();}else render();}else {run=value;patchRuntime();}}catch(e){if(g===generation)onError(e);}finally{refreshing.delete(g);if(g===generation)timer=setTimeout(()=>refresh(g),document.visibilityState==='hidden'?4000:run?.live_message||['starting','running'].includes(run?.agent_state?.status)?450:1400);}}
 function markOrigin(event){const f=event.target.closest('[data-h-form]');if(f&&!inputOrigins.has(key(f.dataset.hForm,'origin')))inputOrigins.set(key(f.dataset.hForm,'origin'),run?.workpapers?.at(-1)?.id||null);}
 async function submit(form){
  if(pending||!form.reportValidity())return;remember();const g=generation,v=Object.fromEntries(new FormData(form)),kind=form.dataset.hKind;
  const beforeRun=run?.id,beforeProject=project.id,beforeRole=roleId,fid=form.dataset.hForm,consentDraftKey=key(form.dataset.hForm,'consent');const cmd={id:crypto.randomUUID(),epoch:run?.epoch,kind,text:v.text};pending=true;form.querySelector('button[type=submit],button:not([type])').disabled=true;
  try{let response;
   if(['create','rework','continue'].includes(kind)){
    response=await api(`/api/projects/${project.id}/harness`,{method:'POST',body:{id:cmd.id,revision:project.revision,role_id:roleId,goal:kind==='create'?v.goal:v.text,...(kind==='continue'?{continue_from:run.id}:{}),...(kind==='rework'?{rework_from:{run_id:run.id,workpaper_id:run.workpapers.at(-1).id}}:{})}});
   }else if(kind==='start'){response=await api(`/api/harness/${run.id}/agent`,{method:'POST',body:{epoch:run.epoch,consent:v.consent==='on',scope:slot._consentScope}});}
   else if(kind==='return'){const data=new FormData(form);data.append('revision',String(project.revision));response=await api(`/api/harness/${run.id}/request-lists/${form.dataset.targetId}/return`,{method:'POST',body:data});if(g===generation)onProject?.(response);return;}
   else if(kind==='record_submission'){form.dataset.submissionRequest ||= crypto.randomUUID();await api(`/api/projects/${project.id}/submissions`,{method:'POST',body:{id:form.dataset.submissionRequest,run_id:run.id,model_id:v.model_id,export_call_id:v.export_call_id,memo_id:v.memo_id,submitted_at:v.submitted_at,submission_reference:v.submission_reference,confirmed_submitted:v.confirmed_submitted==='on'}});response=await api(`/api/harness/${run.id}`);}
   else{
    if(kind==='banker_response'){cmd.todo_id=form.dataset.todoId;cmd.question_signature=form.dataset.todoSignature;cmd.action=v.action;}
    if(['answer','decision_response','completion_response'].includes(kind))cmd.target_id=fid;
    if(['decision_response','completion_response'].includes(kind))cmd.accept=v.accept==='true';
    if(kind==='adopt_model'){const c=run.calls.find(c=>c.id===form.dataset.targetId);cmd.call_id=c.id;cmd.definition_sha256=c.result.report.definition_sha256;cmd.responsible_person=v.responsible_person;}
    if(kind==='approve_request_pack'){const d=run.request_drafts.find(d=>d.id===form.dataset.targetId);cmd.target_id=d.id;cmd.purpose=v.purpose;cmd.fields=d.fields.map((f,i)=>({...f,label:v['label_'+i],entity:v['entity_'+i],period:v['period_'+i],unit:v['unit_'+i],priority:v['priority_'+i],model_use:v['model_use_'+i]}));}
    if(kind==='assumption_change'){const item=run.workpapers.at(-1).items.find(i=>i.id===form.dataset.itemId);cmd.kind='steer';Object.assign(cmd,assumptionChange(item,v));}
    if(['steer','answer','decision_response','completion_response'].includes(cmd.kind)){cmd.intent=v.intent||'revision';cmd.workspace={room_id:cmd.kind==='steer'&&form.matches('.reporting-composer')?currentDiscussionContext()?.room||room:room,workpaper_id:inputOrigins.has(key(fid,'origin'))?inputOrigins.get(key(fid,'origin')):run.workpapers.at(-1)?.id||null,item_ids:form.dataset.itemId?[form.dataset.itemId]:[]};}
    response=await api(`/api/harness/${run.id}/commands`,{method:'POST',body:cmd});
   }
   requireRole(response?.run,beforeRole);
   for(const [name,value]of Object.entries(v)){const k=`${beforeProject}:${beforeRole}:${beforeRun||'new'}:${fid}:${name}`;if(drafts.get(k)===value||name==='consent')drafts.delete(k);}
   inputOrigins.delete(`${beforeProject}:${beforeRole}:${beforeRun||'new'}:${fid}:origin`);if(kind==='start')drafts.delete(consentDraftKey);
   if(['create','rework','continue'].includes(kind))selected.set(`${beforeProject}:${beforeRole}`,response.run.id);
   if(g!==generation)return;
   if(['create','rework','continue'].includes(kind)){selected.set(sessionKey(),response.run.id);slot._runs.unshift(response.run);}
   form.reset();run=response.run;last='';render();
  }catch(e){if(g===generation){const inline=form.querySelector('[data-banker-result],[data-role-result]');if(inline)inline.textContent=e.message;onError(e);}}finally{pending=false;if(g===generation&&form.isConnected)form.querySelector('button[type=submit],button:not([type])').disabled=false;if(g===generation&&reporting)syncReporting();}
 }
 function unmount(){remember();attachments.unmount();discussionContext=null;if(slot)disposeFinancialPresentations(slot);slot?.classList.remove('reporting-slot');slotEvents?.abort();slotEvents=null;generation++;clearTimeout(timer);slot=null;run=null;last='';renderKey='';}
 async function mount(el,p,section=''){
  unmount();slot=el;project=p;room=typeof section==='object'?section.room||'overview':'overview';chatOnly=typeof section==='object'&&section.chatOnly===true;reporting=typeof section==='object'&&section.reporting===true;slot.classList.toggle('reporting-slot',reporting);slot.classList.remove('harness-with-chat');filter=typeof section==='string'?section:'';roleId=typeof section==='object'?section.roleId||'modelling':'modelling';if(typeof section==='object'&&!section.room&&roleCopy[roleId])room=roleCopy[roleId].rooms[0];if(roleId!=='modelling'&&!roleCopy[roleId]){slot.textContent='未登记此工作职责。';onError(new Error('未登记此工作职责。'));return;}if(roleCopy[roleId]&&!roleCopy[roleId].rooms.includes(room)){slot.textContent='此房间不属于当前工作职责。';onError(new Error('此房间不属于当前工作职责。'));return;}if(typeof section==='object'&&section.runId)selected.set(sessionKey(),section.runId);const g=generation;slotEvents=new AbortController();const listenerOptions={signal:slotEvents.signal};slot.textContent='正在读取工作台…';attachments.bind(slot,slotEvents.signal);
  slot.addEventListener('input',e=>{markOrigin(e);if(e.target.matches('[data-h-slider]'))e.target.closest('form').elements.new_value.value=e.target.value;remember();},listenerOptions);
  slot.addEventListener('change',e=>{markOrigin(e);if(e.target.matches('[data-h-month]')){const form=e.target.closest('form'),item=run.workpapers.at(-1).items.find(i=>i.id===form.dataset.itemId);form.elements.new_value.value=item.value[e.target.value];}remember();if(e.target.matches('[data-h-run]')){discussionContext=null;syncDiscussionContext();selected.set(sessionKey(),e.target.value);clearTimeout(timer);generation++;last='';renderKey='';refresh(generation);}},listenerOptions);
  slot.addEventListener('toggle',remember,{...listenerOptions,capture:true});
  slot.addEventListener('submit',e=>{if(e.target.matches('[data-h-form]')){e.preventDefault();e.stopPropagation();submit(e.target);}},listenerOptions);
  slot.addEventListener('click',async e=>{
   if(e.target.closest('[data-reporting-clear-context]')){e.preventDefault();e.stopPropagation();setDiscussionContext(null);return;}
   const roomLink=e.target.closest('[data-reporting-open-room]');if(roomLink){e.preventDefault();e.stopPropagation();const target=roomLink.dataset.reportingOpenRoom,detail={room:target,...(roomLink.dataset.reportingIntent?{intent:roomLink.dataset.reportingIntent}:{}),runId:run?.id||null,roleId,projectId:project.id};if(onOpenRoom)onOpenRoom(target,detail);else slot.dispatchEvent(new CustomEvent('model-studio-open-room',{bubbles:true,detail}));return;}
   if(e.target.closest('[data-open-mission]')){const mission=slot.querySelector('.supervisor-mission');mission.open=true;mission.scrollIntoView({block:'start',behavior:'smooth'});return;}
   const discuss=e.target.closest('[data-banker-discuss],[data-banker-special]');
   if(discuss){const composer=slot.querySelector('.live-chat-composer');if(!composer)return;
    const item=run.workpapers.at(-1)?.items.find(i=>i.id===discuss.dataset.bankerDiscuss);
    composer.elements.text.value=discuss.dataset.bankerSpecial?`请在专项实验室展开${discuss.dataset.bankerSpecial}分析。先按已有资料展示关系和能算出的结果，未知参数用符号说明。`:`请展开“${item?.label||'这项经营设计'}”：列出收入和成本驱动、预测关系及已有数据；不足的参数先用符号示意。`;
    composer.elements.intent.value='revision';composer.elements.text.dispatchEvent(new Event('input',{bubbles:true}));composer.elements.text.focus();return;}
   if(e.target.closest('[data-chat-latest]')){const chat=slot.querySelector('.agent-conversation');if(chat)chat.scrollTop=chat.scrollHeight;return;}
   const rebase=e.target.closest('[data-h-rebase]');if(rebase){inputOrigins.set(key(rebase.closest('[data-h-form]').dataset.hForm,'origin'),run?.workpapers?.at(-1)?.id||null);remember();render();return;}
   const f=e.target.closest('[data-h-filter]');if(f){filter=f.dataset.hFilter;render();return;}
   const b=e.target.closest('[data-h-control]');if(!b||pending)return;pending=true;const own=generation;
   try{const response=await api(`/api/harness/${run.id}/commands`,{method:'POST',body:{id:crypto.randomUUID(),epoch:run.epoch,kind:b.dataset.hControl}});if(own===generation){run=response.run;render();}}catch(err){onError(err);}finally{pending=false;}
  },listenerOptions);
  try{const [data,c]=await Promise.all([api(`/api/projects/${p.id}/harness?role_id=${encodeURIComponent(roleId)}`),api('/api/harness/capabilities')]);if(g!==generation)return;cap=c;slot._runs=(data.runs||[]).filter(r=>roleMatches(r));if(!selected.has(sessionKey())||selected.get(sessionKey())&&!slot._runs.some(r=>r.id===selected.get(sessionKey())))selected.set(sessionKey(),slot._runs[0]?.id||'');await refresh(g);}catch(e){if(g===generation)onError(e);}
 }
 async function updateProject(p){if(!slot||p.id!==project.id)return;project=p;clearTimeout(timer);await refresh(generation);}
 return {mount,unmount,updateProject,setDiscussionContext};
}
